version : '2'

services:
    drupal:
        image: drupal:8.6.1
        ports:
            - 8080:80
        depends_on:
            - postgres
        links:
            - postgres:postgres
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes
        restart: always
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=mysecretpassword
        container_name: some-postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: always
volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
    postgres-data: